# Generated by Django 4.1.6 on 2023-02-04 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0002_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plane', serialize=False, to='flights.airport')),
                ('a1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seata1', to=settings.AUTH_USER_MODEL)),
                ('a2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seata2', to=settings.AUTH_USER_MODEL)),
                ('a3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seata3', to=settings.AUTH_USER_MODEL)),
                ('a4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seata4', to=settings.AUTH_USER_MODEL)),
                ('b1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatb1', to=settings.AUTH_USER_MODEL)),
                ('b2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatb2', to=settings.AUTH_USER_MODEL)),
                ('b3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatb3', to=settings.AUTH_USER_MODEL)),
                ('b4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatb4', to=settings.AUTH_USER_MODEL)),
                ('c1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatc1', to=settings.AUTH_USER_MODEL)),
                ('c2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatc2', to=settings.AUTH_USER_MODEL)),
                ('c3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatc3', to=settings.AUTH_USER_MODEL)),
                ('c4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatc4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.airplane'),
        ),
    ]
